import * as React from "react";
import {
  useWizard,
  type Certification,
  type Skill,
  type SkillsData,
  type Project,
} from "./WizardContext";
import {
  Github,
  Linkedin,
  Twitter,
  ExternalLink,
  Globe,
  Calendar,
  MapPin,
  Sparkles,
  Terminal,
  Award,
  Trophy,
  Code,
  ShieldCheck,
} from "lucide-react";
import { cn, normalizeExternalUrl } from "@/lib/utils";

interface LivePreviewProps {
  isMobileSheet?: boolean;
}

const PREVIEW_DEMO = {
  name: "Demo User",
  initials: "DU",
  role: "Full Stack Developer",
  location: "Sample City",
  tagline: "This is a sample portfolio preview generated by PortfolioForge.",
  bio: "This is a sample portfolio preview generated by PortfolioForge.",
  email: "demo@example.com",
  categorizedSkills: {
    frontend: ["React", "Tailwind CSS"],
    backend: ["Node.js"],
    database: [] as string[],
    languages: ["TypeScript", "Python"],
    tools: [] as string[],
  },
  skills: [
    { name: "React", proficiency: "Advanced" },
    { name: "TypeScript", proficiency: "Advanced" },
    { name: "Node.js", proficiency: "Advanced" },
    { name: "Python", proficiency: "Advanced" },
    { name: "Tailwind CSS", proficiency: "Advanced" },
  ] satisfies Skill[],
  projects: [
    {
      name: "AI Resume Analyzer",
      description:
        "Built an AI-powered tool that parses resumes and extracts structured career data.",
      technologies: ["Python", "React", "OpenAI"],
      link: "",
      githubLink: "https://github.com/demo-user/ai-resume-analyzer",
      image: "",
    },
    {
      name: "Portfolio Builder",
      description:
        "A portfolio generator that turns resume data into polished developer websites.",
      technologies: ["React", "TypeScript", "Tailwind CSS"],
      link: "https://portfolioforge.ai",
      githubLink: "https://github.com/demo-user/portfolio-builder",
      image: "",
    },
    {
      name: "Task Management Dashboard",
      description:
        "Real-time collaborative task board with drag-and-drop and team analytics.",
      technologies: ["Node.js", "React", "PostgreSQL"],
      link: "",
      githubLink: "https://github.com/demo-user/task-dashboard",
      image: "",
    },
  ] satisfies Project[],
  experience: [
    {
      company: "Sample Corp",
      position: "Software Engineer Intern",
      role: "Software Engineer Intern",
      startDate: "Jan 2024",
      endDate: "Present",
      duration: "Jan 2024 - Present",
      location: "Sample City",
      description:
        "Built and shipped full-stack features with React and Node.js for internal developer tools.",
    },
  ],
  education: [
    {
      school: "Sample University",
      institution: "Sample University",
      degree: "B.S. Computer Science",
      fieldOfStudy: "Computer Science",
      startYear: "2020",
      endYear: "2024",
      graduationYear: "2024",
      cgpa: "3.8",
      description: "Focused on software engineering and web development.",
    },
  ],
  certifications: [
    { name: "Cloud Practitioner", issuer: "Sample Cloud Provider", link: "" },
  ] satisfies Certification[],
  awards: ["Dean's List"],
  hackathons: ["Sample Hackathon 2024 Finalist"],
  codingProfiles: {
    github: "demo-user",
    leetcode: "",
    codeforces: "",
    hackerrank: "",
  },
};

export const LivePreview: React.FC<LivePreviewProps> = ({ isMobileSheet }) => {
  const { state } = useWizard();
  const {
    personal,
    education,
    skills,
    categorizedSkills,
    projects,
    experience,
    achievements,
    theme,
    githubAnalytics,
    githubAnalyticsStatus,
  } = state;

  const useDemoPreview = !state.resumeParsed;

  const name = useDemoPreview
    ? PREVIEW_DEMO.name
    : (personal.name || "").trim()
      ? personal.name
      : personal.firstName || personal.lastName
        ? `${personal.firstName} ${personal.lastName}`
        : "Akshaya KV";

  const roleText = useDemoPreview
    ? PREVIEW_DEMO.role
    : personal.role || "Full Stack Developer";
  const taglineText = useDemoPreview
    ? PREVIEW_DEMO.tagline
    : personal.tagline || "Crafting interactive, high-performance web applications.";
  const bio = useDemoPreview
    ? PREVIEW_DEMO.bio
    : personal.bio ||
      "Full Stack Developer specializing in crafting interactive, high-performance web applications. Open to remote opportunities globally.";
  const locationText = useDemoPreview
    ? PREVIEW_DEMO.location
    : personal.location || "Bengaluru, India";
  const emailText = useDemoPreview ? PREVIEW_DEMO.email : personal.email || "akshaya@example.com";
  const photoUrl = useDemoPreview ? "" : personal.profilePhoto || "";
  const avatarInitials = useDemoPreview ? PREVIEW_DEMO.initials : name.charAt(0);

  const hasCategorizedSkills = Object.values(categorizedSkills || {}).some((arr) => arr.length > 0);
  const displayCategorizedSkills = useDemoPreview
    ? PREVIEW_DEMO.categorizedSkills
    : hasCategorizedSkills
      ? categorizedSkills
      : {
          frontend: ["React", "Next.js", "Tailwind CSS"],
          backend: ["Node.js", "Express"],
          database: ["PostgreSQL", "MongoDB"],
          languages: ["TypeScript", "JavaScript", "Python"],
          tools: ["Git", "Docker", "AWS"],
        };

  const displaySkills = useDemoPreview
    ? PREVIEW_DEMO.skills
    : skills.length > 0
      ? skills
      : [
          { name: "React", proficiency: "Expert" },
          { name: "TypeScript", proficiency: "Advanced" },
          { name: "Node.js", proficiency: "Advanced" },
          { name: "Python", proficiency: "Intermediate" },
        ];

  const displayProjects = useDemoPreview
    ? PREVIEW_DEMO.projects
    : projects.length > 0
      ? projects
      : [
          {
            name: "AI Resume Parser & Generator",
            description:
              "Parsed resume PDFs using GPT-4, extracting work history, skills, and compiling them into live portfolio templates in seconds.",
            technologies: ["React", "TypeScript", "Vite", "Node.js", "Zod"],
            link: "https://portfolioforge.ai",
            githubLink: "https://github.com/user/portfolioforge",
            image: "",
          },
        ];

  const displayExperience = useDemoPreview
    ? PREVIEW_DEMO.experience
    : experience.length > 0
      ? experience
      : [
          {
            company: "Razorpay",
            position: "Full Stack Engineer Intern",
            role: "Full Stack Engineer Intern",
            startDate: "June 2024",
            endDate: "Present",
            duration: "June 2024 - Present",
            location: "Bengaluru, India",
            description:
              "Designed core checkout pages with React, handling 50k+ daily queries. Scaled Node.js API server, reducing response latency by 12%.",
          },
        ];

  const displayEducation = useDemoPreview
    ? PREVIEW_DEMO.education
    : education.length > 0
      ? education
      : [
          {
            school: "Vellore Institute of Technology",
            institution: "Vellore Institute of Technology",
            degree: "B.E. Computer Science",
            fieldOfStudy: "Computer Science & Engineering",
            startYear: "2021",
            endYear: "2025",
            graduationYear: "2025",
            cgpa: "8.9",
            description: "Graduated with 8.9 CGPA. Specialization in web architectures.",
          },
        ];

  const displayCerts: Certification[] = useDemoPreview
    ? PREVIEW_DEMO.certifications
    : achievements?.certifications?.length > 0
      ? achievements.certifications
      : [
          { name: "AWS Certified Solutions Architect", issuer: "Amazon Web Services", link: "" },
          { name: "React Developer Certification", issuer: "Meta", link: "" },
        ];
  const displayAwards = useDemoPreview
    ? PREVIEW_DEMO.awards
    : achievements?.awards?.length > 0
      ? achievements.awards
      : ["Dean's List for Academic Excellence"];
  const displayHacks = useDemoPreview
    ? PREVIEW_DEMO.hackathons
    : achievements?.hackathons?.length > 0
      ? achievements.hackathons
      : ["Smart India Hackathon 2024 Winner"];
  const codingProfiles = useDemoPreview
    ? PREVIEW_DEMO.codingProfiles
    : achievements?.codingProfiles || {
        github: "",
        leetcode: "",
        codeforces: "",
        hackerrank: "",
      };
  const certificateLabel = (cert: Certification) =>
    cert.issuer ? `${cert.name} - ${cert.issuer}` : cert.name;

  const renderSkillCertifications = (
    variant: "corporate" | "glass" | "cyber" | "terminal" | "creative" | "saas",
  ) => {
    if (displayCerts.length === 0) return null;

    const styles = {
      corporate: {
        shell: "space-y-1.5",
        title: "text-[9.5px] uppercase font-bold text-slate-400 font-mono tracking-wider",
        list: "flex flex-wrap gap-1.5",
        item: "bg-slate-800 text-slate-300 px-1.5 py-0.5 rounded font-mono text-[9px] border border-slate-700/60",
      },
      glass: {
        shell: "glass p-3 rounded-xl border border-white/5 space-y-1.5",
        title:
          "text-[8.5px] uppercase font-bold text-[var(--cyan-accent)] font-mono tracking-wider block",
        list: "flex flex-wrap gap-1",
        item: "bg-white/5 border border-white/5 text-white/90 px-1.5 py-0.5 rounded-md text-[9.5px] font-mono",
      },
      cyber: {
        shell: "border border-[var(--cyan-accent)]/20 bg-black/50 p-2 space-y-1",
        title: "text-[8px] text-pink-400 uppercase tracking-wider font-bold",
        list: "flex flex-wrap gap-1",
        item: "text-white text-[8.5px] font-bold border border-pink-500/20 bg-pink-500/10 px-1 py-0.5",
      },
      terminal: {
        shell: "text-green-300 pl-2 border-l border-green-900/30 space-y-1",
        title: "text-white font-bold",
        list: "space-y-0.5",
        item: "block text-green-300 text-[10px]",
      },
      creative: {
        shell: "bg-white border-2 border-amber-100 p-3 rounded-xl shadow-sm space-y-1.5",
        title: "text-[9px] font-black text-amber-700 uppercase block",
        list: "flex flex-wrap gap-1",
        item: "bg-[#fefbe8] text-amber-950 px-2 py-0.5 rounded-full font-extrabold text-[9.5px] border border-amber-200",
      },
      saas: {
        shell: "rounded-xl bg-white/5 border border-white/10 p-3 space-y-1.5",
        title:
          "text-[8px] font-mono font-bold uppercase text-[var(--cyan-accent)] tracking-wider block",
        list: "flex flex-wrap gap-1",
        item: "rounded bg-white/5 border border-white/10 px-1.5 py-0.5 text-[9px] font-mono text-muted-foreground",
      },
    }[variant];

    return (
      <div className={styles.shell}>
        <span className={styles.title}>Certifications</span>
        <div className={styles.list}>
          {displayCerts.map((cert, idx) => (
            <span key={`${cert.name}-${idx}`} className={styles.item}>
              {certificateLabel(cert)}
            </span>
          ))}
        </div>
      </div>
    );
  };

  // Address bar URL string
  const addressUrl = `${name.toLowerCase().replace(/\s+/g, "-")}.portfolioforge.ai`;

  const renderPreviewGithubAnalytics = () => {
    if (githubAnalyticsStatus === "loading") {
      return (
        <div className="border-b border-white/10 bg-white/[0.04] px-4 py-3 text-[10px] font-semibold text-muted-foreground">
          Fetching GitHub Analytics...
        </div>
      );
    }

    if (!githubAnalytics) return null;

    return (
      <div className="border-b border-white/10 bg-slate-950/95 px-4 py-3">
        <div className="grid grid-cols-2 gap-2 text-[10px] sm:grid-cols-4">
          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-2">
            <div className="font-mono text-[var(--cyan-accent)]">{githubAnalytics.score}/100</div>
            <div className="text-muted-foreground">GitHub Score</div>
          </div>
          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-2">
            <div className="font-mono text-white">{githubAnalytics.repos}</div>
            <div className="text-muted-foreground">Repositories</div>
          </div>
          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-2">
            <div className="font-mono text-white">{githubAnalytics.followers}</div>
            <div className="text-muted-foreground">Followers</div>
          </div>
          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-2">
            <div className="truncate font-mono text-white">
              {githubAnalytics.topLanguages.slice(0, 2).join(", ") || "None"}
            </div>
            <div className="text-muted-foreground">Top Languages</div>
          </div>
        </div>
      </div>
    );
  };

  // Render Theme View
  const renderThemeView = () => {
    switch (theme) {
      case "corporate":
        return (
          <div className="bg-slate-900 text-slate-100 font-sans p-6 min-h-full space-y-8 select-none text-[12px] leading-relaxed">
            {/* Header */}
            <div className="border-b border-slate-800 pb-4 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                {photoUrl ? (
                  <img
                    src={photoUrl}
                    alt={name}
                    className="h-12 w-12 rounded-full object-cover border border-slate-700 shrink-0"
                  />
                ) : (
                  <div className="h-12 w-12 rounded-full bg-blue-500/10 text-blue-400 font-bold flex items-center justify-center border border-slate-800 text-sm shrink-0">
                    {avatarInitials}
                  </div>
                )}
                <div>
                  <h1 className="text-base font-bold text-slate-100">{name}</h1>
                  <p className="text-[11px] text-blue-400 font-semibold">{roleText}</p>
                </div>
              </div>
              <div className="text-right text-[9px] text-slate-400 shrink-0">
                <p>{emailText}</p>
                <p>{locationText}</p>
              </div>
            </div>

            {/* Tagline */}
            <div className="bg-slate-950/40 border border-slate-800 p-3 rounded-lg">
              <p className="text-[11px] font-medium text-slate-300 font-serif leading-relaxed italic">
                "{taglineText}"
              </p>
            </div>

            {/* About */}
            <div className="space-y-1.5">
              <h2 className="text-[10px] uppercase tracking-wider text-blue-400 font-bold">
                Profile Summary
              </h2>
              <p className="text-slate-300 font-serif text-[11px] leading-relaxed italic">
                "{bio}"
              </p>
            </div>

            {/* Experience */}
            <div className="space-y-3">
              <h2 className="text-[10px] uppercase tracking-wider text-blue-400 font-bold border-b border-slate-800 pb-1">
                Professional Experience
              </h2>
              <div className="space-y-3">
                {displayExperience.map((exp, i) => (
                  <div key={i} className="space-y-1">
                    <div className="flex justify-between font-bold text-slate-200">
                      <span>
                        {exp.position || exp.role} — {exp.company}
                      </span>
                      <span className="font-normal text-slate-400 text-[9px]">
                        {exp.startDate || exp.duration?.split(" - ")[0]} -{" "}
                        {exp.endDate || exp.duration?.split(" - ")[1]}
                      </span>
                    </div>
                    {exp.location && (
                      <div className="text-[9px] text-slate-400 font-medium">{exp.location}</div>
                    )}
                    <p className="text-slate-300 text-[10.5px] leading-relaxed mt-1">
                      {exp.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Categorized Skills */}
            <div className="space-y-3">
              <h2 className="text-[10px] uppercase tracking-wider text-blue-400 font-bold border-b border-slate-800 pb-1">
                Technical Skills
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div key={catName} className="space-y-1">
                      <span className="text-[9.5px] uppercase font-bold text-slate-400 font-mono tracking-wider">
                        {catName}
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {list.map((s, idx) => (
                          <span
                            key={idx}
                            className="bg-slate-800 text-slate-300 px-1.5 py-0.5 rounded font-mono text-[9px] border border-slate-700/60"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("corporate")}
            </div>

            {/* Projects */}
            <div className="space-y-3">
              <h2 className="text-[10px] uppercase tracking-wider text-blue-400 font-bold border-b border-slate-800 pb-1">
                Key Projects
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {displayProjects.map((p, i) => (
                  <div
                    key={i}
                    className="border border-slate-800 bg-slate-950/20 p-3 rounded-lg flex flex-col justify-between"
                  >
                    <div>
                      {p.image && (
                        <img
                          src={p.image}
                          alt={p.name}
                          className="h-20 w-full object-cover rounded-md mb-2 border border-slate-800"
                        />
                      )}
                      <div className="font-bold text-slate-200 flex items-center justify-between gap-2">
                        <span className="truncate">{p.name}</span>
                        <div className="flex gap-1.5 shrink-0">
                          {p.githubLink && (
                            <a href={normalizeExternalUrl(p.githubLink)}>
                              <Github className="h-3 w-3 text-slate-400 hover:text-white" />
                            </a>
                          )}
                          {p.link && (
                            <a href={normalizeExternalUrl(p.link)}>
                              <ExternalLink className="h-3 w-3 text-blue-400" />
                            </a>
                          )}
                        </div>
                      </div>
                      <p className="text-slate-400 text-[10px] mt-1.5 line-clamp-3 leading-normal">
                        {p.description}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2.5">
                      {p.technologies.map((t) => (
                        <span
                          key={t}
                          className="text-[8.5px] bg-slate-800 text-slate-400 px-1.5 py-0.2 rounded font-mono"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Achievements */}
            <div className="space-y-3">
              <h2 className="text-[10px] uppercase tracking-wider text-blue-400 font-bold border-b border-slate-800 pb-1">
                Certifications & Achievements
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {/* Certifications */}
                {displayCerts.length > 0 && (
                  <div className="space-y-1">
                    <span className="text-[9.5px] uppercase font-bold text-slate-400">
                      Certifications
                    </span>
                    <ul className="list-disc list-inside space-y-0.5 text-slate-300 text-[10px]">
                      {displayCerts.map((c, idx) => (
                        <li key={idx} className="truncate">
                          {certificateLabel(c)}
                          {c.fileData && (
                            <a href={c.fileData} className="ml-1 text-blue-400">
                              pdf
                            </a>
                          )}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {/* Awards */}
                {displayAwards.length > 0 && (
                  <div className="space-y-1">
                    <span className="text-[9.5px] uppercase font-bold text-slate-400">
                      Awards & Hackathons
                    </span>
                    <ul className="list-disc list-inside space-y-0.5 text-slate-300 text-[10px]">
                      {[...displayAwards, ...displayHacks].map((aw, idx) => (
                        <li key={idx} className="truncate">
                          {aw}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </div>
          </div>
        );

      case "glass":
        return (
          <div className="bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-950 via-slate-950 to-black text-white p-6 min-h-full space-y-8 select-none text-[12px] relative overflow-hidden font-sans">
            {/* Blurry backing blobs */}
            <div className="absolute top-10 right-10 h-32 w-32 bg-[var(--cyan-accent)]/10 rounded-full blur-3xl" />
            <div className="absolute bottom-10 left-10 h-32 w-32 bg-indigo-500/10 rounded-full blur-3xl" />

            {/* Profile Header card */}
            <div className="glass rounded-2xl p-5 space-y-3 relative z-10">
              <div className="flex items-center gap-3">
                {photoUrl ? (
                  <img
                    src={photoUrl}
                    alt={name}
                    className="h-14 w-14 rounded-xl object-cover border border-white/10 shrink-0 shadow-lg"
                  />
                ) : (
                  <div className="h-14 w-14 rounded-xl bg-gradient-brand flex items-center justify-center font-bold text-white text-base shadow-glow shrink-0">
                    {avatarInitials}
                  </div>
                )}
                <div className="min-w-0">
                  <h1 className="text-base font-bold tracking-tight text-white truncate">{name}</h1>
                  <p className="text-[10px] font-mono text-[var(--cyan-accent)] uppercase tracking-wider mt-0.5">
                    {roleText}
                  </p>
                </div>
              </div>
              <p className="text-white/80 leading-relaxed text-[11px] font-serif italic">
                "{taglineText}"
              </p>
            </div>

            {/* Categorized Skills */}
            <div className="space-y-3 relative z-10">
              <h2 className="text-[10px] font-mono uppercase tracking-widest text-indigo-300">
                Technical Stack
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div
                      key={catName}
                      className="glass p-3 rounded-xl border border-white/5 space-y-1.5"
                    >
                      <span className="text-[8.5px] uppercase font-bold text-[var(--cyan-accent)] font-mono tracking-wider block">
                        {catName}
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {list.map((s, idx) => (
                          <span
                            key={idx}
                            className="bg-white/5 border border-white/5 text-white/90 px-1.5 py-0.5 rounded-md text-[9.5px] font-mono"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("glass")}
            </div>

            {/* Experience timeline */}
            <div className="space-y-3 relative z-10">
              <h2 className="text-[10px] font-mono uppercase tracking-widest text-indigo-300">
                Experience
              </h2>
              <div className="space-y-3">
                {displayExperience.map((exp, i) => (
                  <div key={i} className="glass rounded-xl p-3 border border-white/5 space-y-1">
                    <div className="flex justify-between font-bold text-white text-[11px]">
                      <span>{exp.position || exp.role}</span>
                      <span className="text-[9px] font-mono text-white/60">
                        {exp.startDate || exp.duration?.split(" - ")[0]}
                      </span>
                    </div>
                    <div className="text-[10px] text-[var(--cyan-accent)] font-semibold">
                      {exp.company}
                    </div>
                    <p className="text-white/70 text-[10px] mt-1 leading-normal">
                      {exp.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Projects */}
            <div className="space-y-3 relative z-10">
              <h2 className="text-[10px] font-mono uppercase tracking-widest text-indigo-300">
                Featured Builds
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {displayProjects.map((p, i) => (
                  <div
                    key={i}
                    className="glass rounded-xl p-3 border border-white/5 flex flex-col justify-between space-y-2"
                  >
                    <div>
                      {p.image && (
                        <img
                          src={p.image}
                          alt={p.name}
                          className="h-20 w-full object-cover rounded-lg mb-2 border border-white/5"
                        />
                      )}
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-bold text-white truncate text-[11px]">{p.name}</span>
                        <div className="flex gap-2 shrink-0">
                          {p.githubLink && (
                            <a href={normalizeExternalUrl(p.githubLink)}>
                              <Github className="h-3 w-3 text-white/60 hover:text-white" />
                            </a>
                          )}
                          {p.link && (
                            <a href={normalizeExternalUrl(p.link)}>
                              <ExternalLink className="h-3 w-3 text-[var(--cyan-accent)]" />
                            </a>
                          )}
                        </div>
                      </div>
                      <p className="text-white/70 text-[10px] leading-relaxed mt-1 line-clamp-3">
                        {p.description}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1 pt-1">
                      {p.technologies.map((t) => (
                        <span
                          key={t}
                          className="text-[8px] font-mono rounded bg-white/5 text-white/60 border border-white/5 px-1 py-0.2"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Achievements & Coding Profiles */}
            <div className="space-y-3 relative z-10">
              <h2 className="text-[10px] font-mono uppercase tracking-widest text-indigo-300">
                Credentials & Profiles
              </h2>
              <div className="glass rounded-xl p-3 border border-white/5 grid gap-3 sm:grid-cols-2">
                {displayCerts.length > 0 && (
                  <div className="space-y-1">
                    <span className="text-[9px] uppercase font-bold text-[var(--cyan-accent)] tracking-wider">
                      Certifications
                    </span>
                    <ul className="space-y-1 text-white/80 text-[10px]">
                      {displayCerts.map((c, idx) => (
                        <li key={idx} className="flex items-center gap-1.5 truncate">
                          <Award className="h-3 w-3 text-indigo-400 shrink-0" />
                          <span className="truncate">{certificateLabel(c)}</span>
                          {c.fileData && (
                            <a href={c.fileData} className="text-indigo-300 shrink-0">
                              PDF
                            </a>
                          )}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                <div className="space-y-1.5">
                  <span className="text-[9px] uppercase font-bold text-[var(--cyan-accent)] tracking-wider block">
                    Profiles
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {codingProfiles.github && (
                      <a
                        href={codingProfiles.github}
                        className="glass p-1.5 rounded-lg text-white/80 hover:text-white flex items-center justify-center"
                      >
                        <Github className="h-3.5 w-3.5" />
                      </a>
                    )}
                    {codingProfiles.leetcode && (
                      <a
                        href={codingProfiles.leetcode}
                        className="glass p-1.5 rounded-lg text-amber-400 hover:text-amber-300 flex items-center justify-center text-[9px] font-bold font-mono px-2"
                      >
                        LC
                      </a>
                    )}
                    {codingProfiles.codeforces && (
                      <a
                        href={codingProfiles.codeforces}
                        className="glass p-1.5 rounded-lg text-blue-400 hover:text-blue-300 flex items-center justify-center text-[9px] font-bold font-mono px-2"
                      >
                        CF
                      </a>
                    )}
                    {codingProfiles.hackerrank}
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "cyber":
        return (
          <div className="bg-black text-[var(--cyan-accent)] font-mono p-5 min-h-full space-y-6 select-none text-[11px] relative overflow-hidden border border-hot-pink">
            <div className="absolute inset-0 grid-bg opacity-10" />

            {/* Top flashing badge */}
            <div className="flex justify-between items-center border border-[var(--cyan-accent)]/20 p-2 bg-slate-950/40">
              <div className="text-[9px] uppercase tracking-widest flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-pink-500 animate-ping" />
                SYSTEM ACTIVE // PORTFOLIO_V2
              </div>
              <div className="text-[8.5px]">STK_ID: {name.slice(0, 3).toUpperCase()}</div>
            </div>

            {/* Personal bio */}
            <div className="flex flex-col sm:flex-row gap-4 border-l-2 border-pink-500 pl-3 relative z-10">
              {photoUrl && (
                <img
                  src={photoUrl}
                  alt={name}
                  className="h-14 w-14 rounded-md object-cover border border-[var(--cyan-accent)]/30 shrink-0 mb-2 sm:mb-0"
                />
              )}
              <div>
                <h1 className="text-base font-extrabold text-white uppercase tracking-wider">
                  {name}
                </h1>
                <div className="text-[8.5px] text-pink-500 uppercase tracking-widest font-bold">
                  {roleText} // {locationText}
                </div>
                <p className="text-slate-300 leading-normal font-sans text-xs mt-2 italic">
                  "{taglineText}"
                </p>
              </div>
            </div>

            {/* Categorized Skills */}
            <div className="space-y-2">
              <div className="text-[10px] text-pink-500 font-bold uppercase tracking-wider">
                // SYSTEM_CORE_SKILLS
              </div>
              <div className="grid gap-2 grid-cols-2">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div
                      key={catName}
                      className="border border-[var(--cyan-accent)]/20 bg-black/50 p-2 space-y-1"
                    >
                      <span className="text-[8px] text-pink-400 uppercase tracking-wider font-bold">
                        [{catName.toUpperCase()}]
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {list.map((s, idx) => (
                          <span key={idx} className="text-white text-[8.5px] font-bold">
                            {s}
                            {idx < list.length - 1 ? "," : ""}
                          </span>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("cyber")}
            </div>

            {/* Experience */}
            <div className="space-y-3">
              <div className="text-[10px] text-pink-500 font-bold uppercase tracking-wider">
                // WORK_HISTORY_LOG
              </div>
              {displayExperience.map((exp, i) => (
                <div
                  key={i}
                  className="border border-[var(--cyan-accent)]/20 p-3 bg-slate-950/20 space-y-1"
                >
                  <div className="flex justify-between text-white font-bold">
                    <span>
                      {exp.company} :: {exp.position || exp.role}
                    </span>
                    <span className="text-pink-500 text-[8.5px]">
                      {exp.startDate || exp.duration?.split(" - ")[0]}
                    </span>
                  </div>
                  <p className="text-slate-300 text-[9.5px] leading-relaxed pt-1 font-sans">
                    {exp.description}
                  </p>
                </div>
              ))}
            </div>

            {/* Projects */}
            <div className="space-y-3">
              <div className="text-[10px] text-pink-500 font-bold uppercase tracking-wider">
                // EXECUTABLE_BUILDS
              </div>
              <div className="grid gap-3 sm:grid-cols-2">
                {displayProjects.map((p, i) => (
                  <div
                    key={i}
                    className="border border-pink-500/20 p-2.5 space-y-2 bg-black/60 flex flex-col justify-between"
                  >
                    <div>
                      {p.image && (
                        <img
                          src={p.image}
                          alt={p.name}
                          className="h-16 w-full object-cover rounded border border-pink-500/25 mb-1.5"
                        />
                      )}
                      <div className="text-white font-bold uppercase tracking-wider flex items-center justify-between">
                        <span className="truncate">{p.name}</span>
                        <div className="flex gap-2">
                          {p.githubLink && (
                            <a
                              href={normalizeExternalUrl(p.githubLink)}
                              className="text-[var(--cyan-accent)] hover:text-white"
                            >
                              SRC
                            </a>
                          )}
                          {p.link && (
                            <a
                              href={normalizeExternalUrl(p.link)}
                              className="text-pink-400 hover:text-white"
                            >
                              DEMO
                            </a>
                          )}
                        </div>
                      </div>
                      <p className="text-slate-300 text-[9px] leading-relaxed font-sans mt-1 line-clamp-3">
                        {p.description}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1 pt-1.5">
                      {p.technologies.map((t) => (
                        <span
                          key={t}
                          className="text-[8px] bg-pink-500/10 border border-pink-500/20 text-pink-400 px-1 py-0.2"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Achievements */}
            <div className="space-y-2.5">
              <div className="text-[10px] text-pink-500 font-bold uppercase tracking-wider">
                // ACCREDITATION_EXPORTS
              </div>
              <div className="border border-[var(--cyan-accent)]/20 p-3 bg-black/50 space-y-1.5 text-slate-300 text-[9px]">
                {displayCerts.map((c, idx) => (
                  <div key={idx}>• CERT: {certificateLabel(c).toUpperCase()}</div>
                ))}
                {displayAwards.map((a, idx) => (
                  <div key={idx}>• AWARD: {a.toUpperCase()}</div>
                ))}
                {displayHacks.map((h, idx) => (
                  <div key={idx}>• HACK: {h.toUpperCase()}</div>
                ))}
              </div>
            </div>
          </div>
        );

      case "terminal":
        return (
          <div className="bg-black text-green-400 font-mono p-5 min-h-full space-y-6 select-none text-[11px] leading-normal">
            <div className="flex items-center gap-1.5 border-b border-green-900/30 pb-3">
              <Terminal className="h-4.5 w-4.5 text-green-500" />
              <span className="text-[10px] text-green-500">guest@portfolioforge.sh: ~/profile</span>
            </div>

            {/* bio command */}
            <div className="space-y-1">
              <div className="text-green-500/60 font-semibold">$ cat whoami.md</div>
              <div className="flex items-center gap-3">
                {photoUrl && (
                  <img
                    src={photoUrl}
                    alt={name}
                    className="h-10 w-10 rounded-md object-cover border border-green-800 shrink-0"
                  />
                )}
                <div>
                  <div className="text-white font-bold text-sm">{name}</div>
                  <div className="text-green-500/70 text-[9px]">
                    {roleText} | {locationText}
                  </div>
                </div>
              </div>
              <div className="text-green-300 font-sans mt-2 leading-relaxed text-[11px] italic">
                "{taglineText}"
              </div>
            </div>

            {/* skills command */}
            <div className="space-y-1.5">
              <div className="text-green-500/60 font-semibold">$ cat skills/categorized.json</div>
              <div className="text-green-300 pl-2 border-l border-green-900/30 space-y-1">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div key={catName}>
                      <span className="text-white font-bold">"{catName}":</span> ["
                      {list.join('", "')}"]
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("terminal")}
            </div>

            {/* experience command */}
            <div className="space-y-2">
              <div className="text-green-500/60 font-semibold">$ cat work_history.json</div>
              <div className="space-y-2.5 pl-2 border-l border-green-900/50">
                {displayExperience.map((exp, i) => (
                  <div key={i} className="space-y-0.5">
                    <div className="text-white font-bold font-mono">
                      "{exp.position || exp.role} @ {exp.company}"
                    </div>
                    <div className="text-green-500/85 text-[9px]">
                      {exp.startDate || exp.duration?.split(" - ")[0]} -{" "}
                      {exp.endDate || exp.duration?.split(" - ")[1]}
                    </div>
                    <p className="text-green-300/90 font-sans leading-normal text-[10px] mt-0.5">
                      {exp.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* projects command */}
            <div className="space-y-2">
              <div className="text-green-500/60 font-semibold">$ find builds/ -type f</div>
              <div className="space-y-2">
                {displayProjects.map((p, i) => (
                  <div key={i} className="pl-2 border-l border-green-900/50">
                    <span className="text-white font-bold">
                      builds/{p.name.replace(/\s+/g, "_").toLowerCase()}.bin
                    </span>
                    <p className="text-green-300/80 text-[10px] font-sans mt-0.5 leading-normal">
                      {p.description}
                    </p>
                    <div className="text-green-500/60 text-[8.5px] mt-0.5">
                      Stack: {p.technologies.join(", ")}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* achievements command */}
            <div className="space-y-2">
              <div className="text-green-500/60 font-semibold">$ cat achievements.txt</div>
              <div className="text-green-200 space-y-0.5">
                {displayCerts.map((c, idx) => (
                  <div key={idx}>[CERT] {certificateLabel(c)}</div>
                ))}
                {displayAwards.map((a, idx) => (
                  <div key={idx}>[AWARD] {a}</div>
                ))}
                {displayHacks.map((h, idx) => (
                  <div key={idx}>[HACK] {h}</div>
                ))}
              </div>
            </div>

            {/* Blinking prompt line */}
            <div className="flex items-center gap-1.5 pt-2">
              <span>guest@portfolioforge.sh: ~/profile$</span>
              <span className="h-3 w-1.5 bg-green-400 animate-pulse" />
            </div>
          </div>
        );

      case "creative":
        return (
          <div className="bg-[#fefbe8] text-amber-950 font-sans p-6 min-h-full space-y-8 select-none text-[12px] leading-relaxed">
            {/* profile block */}
            <div className="space-y-3 text-center">
              <div className="inline-block h-16 w-16 rounded-full bg-gradient-to-tr from-amber-500 to-purple-600 p-0.5 mx-auto relative">
                {photoUrl ? (
                  <img
                    src={photoUrl}
                    alt={name}
                    className="h-full w-full object-cover rounded-full border-2 border-[#fefbe8]"
                  />
                ) : (
                  <div className="h-full w-full rounded-full bg-[#fefbe8] flex items-center justify-center font-bold text-base text-amber-950">
                    {avatarInitials}
                  </div>
                )}
              </div>
              <div>
                <h1 className="text-[17px] font-black tracking-tight text-amber-950">{name}</h1>
                <p className="text-[10px] font-extrabold text-purple-700 uppercase tracking-widest mt-0.5">
                  {roleText} // {locationText}
                </p>
              </div>
              <p className="max-w-md mx-auto text-amber-900 text-[10.5px] italic font-semibold leading-normal bg-amber-50/60 border border-amber-100/80 p-3 rounded-2xl">
                "{taglineText}"
              </p>
            </div>

            {/* Categorized Skills */}
            <div className="space-y-3">
              <h2 className="text-xs font-black uppercase tracking-wider text-purple-700">
                Capabilities
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div
                      key={catName}
                      className="bg-white border-2 border-amber-100 p-3 rounded-xl shadow-sm"
                    >
                      <span className="text-[9px] font-black text-amber-700 uppercase block mb-1">
                        {catName}
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {list.map((s, idx) => (
                          <span
                            key={idx}
                            className="bg-[#fefbe8] text-amber-950 px-2 py-0.5 rounded-full font-extrabold text-[9.5px] border border-amber-200"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("creative")}
            </div>

            {/* Experience */}
            <div className="space-y-3">
              <h2 className="text-xs font-black uppercase tracking-wider text-purple-700">
                Experience Journey
              </h2>
              <div className="space-y-3">
                {displayExperience.map((exp, i) => (
                  <div
                    key={i}
                    className="bg-white border-2 border-amber-100 p-3.5 rounded-2xl shadow-sm space-y-1"
                  >
                    <div className="flex justify-between font-black text-amber-950 text-xs">
                      <span>{exp.position || exp.role}</span>
                      <span className="font-bold text-purple-700 text-[9.5px]">
                        {exp.startDate || exp.duration?.split(" - ")[0]}
                      </span>
                    </div>
                    <div className="text-[9.5px] font-bold text-amber-700 uppercase">
                      {exp.company}
                    </div>
                    <p className="text-amber-900 text-[10px] leading-relaxed mt-1.5">
                      {exp.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Projects */}
            <div className="space-y-3">
              <h2 className="text-xs font-black uppercase tracking-wider text-purple-700">
                Creations
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {displayProjects.map((p, i) => (
                  <div
                    key={i}
                    className="bg-white border-2 border-purple-100 p-3 rounded-2xl flex flex-col justify-between shadow-sm"
                  >
                    <div>
                      {p.image && (
                        <img
                          src={p.image}
                          alt={p.name}
                          className="h-20 w-full object-cover rounded-xl border border-purple-50/10 mb-2"
                        />
                      )}
                      <h3 className="font-black text-amber-950 text-xs flex items-center justify-between gap-2">
                        <span className="truncate">{p.name}</span>
                        <div className="flex gap-2">
                          {p.githubLink && (
                            <a href={normalizeExternalUrl(p.githubLink)}>
                              <Github className="h-3.5 w-3.5 text-purple-600" />
                            </a>
                          )}
                          {p.link && (
                            <a href={normalizeExternalUrl(p.link)}>
                              <Globe className="h-3.5 w-3.5 text-amber-700" />
                            </a>
                          )}
                        </div>
                      </h3>
                      <p className="text-amber-900 text-[9.5px] leading-normal mt-1 line-clamp-3">
                        {p.description}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2 pt-1">
                      {p.technologies.map((t) => (
                        <span
                          key={t}
                          className="text-[8px] bg-purple-50 text-purple-700 px-2 py-0.2 rounded font-bold"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Achievements */}
            <div className="space-y-3">
              <h2 className="text-xs font-black uppercase tracking-wider text-purple-700">
                Certificates & Awards
              </h2>
              <div className="bg-white border-2 border-amber-100 p-3.5 rounded-2xl shadow-sm space-y-1.5 text-[10px] text-amber-900 font-medium">
                {displayCerts.map((c, idx) => (
                  <div key={idx} className="flex items-center gap-1.5">
                    <Award className="h-3.5 w-3.5 text-purple-600 shrink-0" /> {certificateLabel(c)}
                  </div>
                ))}
                {displayAwards.map((a, idx) => (
                  <div key={idx} className="flex items-center gap-1.5">
                    <Trophy className="h-3.5 w-3.5 text-amber-600 shrink-0" /> {a}
                  </div>
                ))}
              </div>
            </div>
          </div>
        );

      // Default to "saas"
      case "saas":
      default:
        return (
          <div className="bg-[#030712] text-white p-6 min-h-full space-y-8 select-none text-[12px] leading-normal font-sans">
            {/* Header */}
            <div className="flex items-center justify-between pb-4 border-b border-white/5 gap-4">
              <div className="flex items-center gap-3">
                {photoUrl ? (
                  <img
                    src={photoUrl}
                    alt={name}
                    className="h-12 w-12 rounded-xl object-cover border border-white/10 shrink-0 shadow-lg"
                  />
                ) : (
                  <div className="h-12 w-12 rounded-xl bg-gradient-brand flex items-center justify-center font-extrabold text-white text-sm shrink-0">
                    {avatarInitials}
                  </div>
                )}
                <div>
                  <h1 className="text-[14px] font-extrabold tracking-tight text-white">{name}</h1>
                  <p className="text-[9.5px] text-muted-foreground font-semibold mt-0.5">
                    {roleText}
                  </p>
                </div>
              </div>
              <div className="flex gap-2.5 shrink-0">
                {personal.github && (
                  <a href={personal.github}>
                    <Github className="h-4 w-4 text-muted-foreground hover:text-white" />
                  </a>
                )}
                {personal.linkedin && (
                  <a href={personal.linkedin}>
                    <Linkedin className="h-4 w-4 text-muted-foreground hover:text-white" />
                  </a>
                )}
              </div>
            </div>

            {/* Tagline */}
            <p className="text-white/80 text-xs leading-normal font-semibold border-l-2 border-[var(--cyan-accent)] pl-2.5">
              {taglineText}
            </p>

            {/* Bio */}
            <p className="text-muted-foreground text-[10.5px] leading-relaxed">{bio}</p>

            {/* Experience */}
            <div className="space-y-4">
              <h2 className="text-[9px] uppercase font-bold tracking-widest text-slate-400">
                // EXPERIENCE
              </h2>
              <div className="space-y-4">
                {displayExperience.map((exp, i) => (
                  <div key={i} className="space-y-1.5 relative pl-4 border-l border-white/5">
                    <div className="absolute -left-[4.5px] top-1 h-2 w-2 rounded-full bg-gradient-brand shadow-sm" />
                    <div className="flex justify-between items-start text-[11px]">
                      <div className="font-semibold text-white">{exp.position || exp.role}</div>
                      <div className="text-[8.5px] font-mono text-muted-foreground">
                        {exp.startDate || exp.duration?.split(" - ")[0]}
                      </div>
                    </div>
                    <div className="text-[9.5px] text-gradient-brand font-bold">{exp.company}</div>
                    <p className="text-muted-foreground text-[10px] leading-normal mt-1">
                      {exp.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Categorized Skills */}
            <div className="space-y-3">
              <h2 className="text-[9px] uppercase font-bold tracking-widest text-slate-400">
                // TECHNICAL CAPABILITIES
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {Object.entries(displayCategorizedSkills).map(([catName, list]) => {
                  if (!list || list.length === 0) return null;
                  return (
                    <div
                      key={catName}
                      className="rounded-xl bg-white/5 border border-white/10 p-3 space-y-1.5"
                    >
                      <span className="text-[8px] font-mono font-bold uppercase text-[var(--cyan-accent)] tracking-wider block">
                        {catName}
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {list.map((s, idx) => (
                          <span
                            key={idx}
                            className="rounded bg-white/5 border border-white/10 px-1.5 py-0.5 text-[9px] font-mono text-muted-foreground"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              {renderSkillCertifications("saas")}
            </div>

            {/* Projects */}
            <div className="space-y-4">
              <h2 className="text-[9px] uppercase font-bold tracking-widest text-slate-400">
                // RECENT BUILDS
              </h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {displayProjects.map((p, i) => (
                  <div
                    key={i}
                    className="rounded-xl bg-white/5 border border-white/10 p-3.5 space-y-2 flex flex-col justify-between"
                  >
                    <div>
                      {p.image && (
                        <img
                          src={p.image}
                          alt={p.name}
                          className="h-20 w-full object-cover rounded-lg border border-white/5 mb-2"
                        />
                      )}
                      <div className="font-semibold text-white flex items-center justify-between gap-2 text-[11px]">
                        <span className="truncate">{p.name}</span>
                        <div className="flex gap-2">
                          {p.githubLink && (
                            <a href={normalizeExternalUrl(p.githubLink)}>
                              <Github className="h-3.5 w-3.5 text-muted-foreground hover:text-white" />
                            </a>
                          )}
                          {p.link && (
                            <a href={normalizeExternalUrl(p.link)}>
                              <ExternalLink className="h-3.5 w-3.5 text-[var(--cyan-accent)]" />
                            </a>
                          )}
                        </div>
                      </div>
                      <p className="text-muted-foreground text-[10px] leading-normal mt-1 line-clamp-3">
                        {p.description}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2.5">
                      {p.technologies.map((t) => (
                        <span key={t} className="text-[8.5px] font-mono text-white/50">
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Achievements */}
            <div className="space-y-3">
              <h2 className="text-[9px] uppercase font-bold tracking-widest text-slate-400">
                // ACCOMPLISHMENTS
              </h2>
              <div className="rounded-xl bg-white/5 border border-white/10 p-3.5 grid gap-3 sm:grid-cols-2 text-[10px] text-muted-foreground">
                {displayCerts.length > 0 && (
                  <div className="space-y-1">
                    <span className="text-[8.5px] font-mono text-[var(--cyan-accent)] uppercase block mb-1">
                      Certifications
                    </span>
                    {displayCerts.map((c, idx) => (
                      <div key={idx} className="truncate">
                        • {certificateLabel(c)}
                      </div>
                    ))}
                  </div>
                )}
                {displayAwards.length > 0 && (
                  <div className="space-y-1">
                    <span className="text-[8.5px] font-mono text-[var(--cyan-accent)] uppercase block mb-1">
                      Honors & Awards
                    </span>
                    {displayAwards.map((a, idx) => (
                      <div key={idx} className="truncate">
                        • {a}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div
      className={cn(
        "rounded-2xl border border-white/5 bg-slate-950 overflow-hidden flex flex-col shadow-2xl relative",
        isMobileSheet ? "h-full" : "h-[450px] xl:h-[500px]",
      )}
    >
      {/* Mock Browser Title Bar */}
      <div className="bg-slate-900 border-b border-white/5 px-4 py-2.5 flex items-center shrink-0">
        <div className="flex gap-1.5 items-center mr-4">
          <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.7_0.18_25)]" />
          <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.78_0.15_85)]" />
          <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.7_0.16_150)]" />
        </div>
        <div className="flex-1 bg-black/35 rounded-md px-2.5 py-0.5 flex items-center justify-center text-[10px] text-muted-foreground font-mono truncate select-none border border-white/5">
          {addressUrl}
        </div>
      </div>

      {/* Browser Main Scroll Window */}
      <div className="flex-1 overflow-y-auto bg-slate-950 scroll-smooth relative">
        {/* AI Resume Banner */}
        {state.resumeParsed && (
          <div className="sticky top-0 z-20 flex items-center justify-center gap-1.5 bg-emerald-500/10 border-b border-emerald-500/20 px-3 py-1.5 backdrop-blur-sm">
            <Sparkles className="h-3 w-3 text-emerald-400 shrink-0" />
            <span className="text-[10px] font-semibold text-emerald-300 tracking-wide">
              ✨ Auto-populated from your resume
            </span>
          </div>
        )}
        {renderPreviewGithubAnalytics()}
        {renderThemeView()}
      </div>
    </div>
  );
};
