import { motion, useInView, useMotionValue, useSpring, type Variants } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import {
  ArrowRight, Sparkles, Upload, Brain, Palette, Globe, Rocket, FileText,
  Github, Linkedin, Twitter, Check, Code2, GraduationCap,
  Zap, Layers, Download, Menu, X, Cpu, Trophy,
} from "lucide-react";

/* ───────────────────── helpers ───────────────────── */

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1];
const LANDING_DEMO = {
  name: "Demo User",
  initials: "DU",
  role: "Full Stack Developer",
  location: "Sample City",
  bio: "This is a sample portfolio preview generated by PortfolioForge.",
  skills: ["React", "TypeScript", "Node.js", "Python", "Tailwind CSS"],
  projects: ["AI Resume Analyzer", "Portfolio Builder", "Task Management Dashboard"],
  githubUsername: "demo-user",
};
const fadeUp: Variants = {
  hidden: { opacity: 0, y: 24 },
  show: (i: number = 0) => ({ opacity: 1, y: 0, transition: { duration: 0.6, delay: i * 0.08, ease: EASE } }),
};

function Counter({ to, suffix = "", duration = 2 }: { to: number; suffix?: string; duration?: number }) {
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: "-50px" });
  const mv = useMotionValue(0);
  const spring = useSpring(mv, { duration: duration * 1000, bounce: 0 });
  const [val, setVal] = useState(0);

  useEffect(() => { if (inView) mv.set(to); }, [inView, to, mv]);
  useEffect(() => spring.on("change", (v) => setVal(Math.floor(v))), [spring]);

  return <span ref={ref}>{val.toLocaleString()}{suffix}</span>;
}

/* ───────────────────── navbar ───────────────────── */

function Navbar() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 12);
    fn(); window.addEventListener("scroll", fn);
    return () => window.removeEventListener("scroll", fn);
  }, []);

  const nav = [
    { label: "Features", href: "#features" },
    { label: "Templates", href: "#templates" },
    { label: "How It Works", href: "#how" },
    { label: "About", href: "#about" },
  ];

  return (
    <header className={`fixed top-0 inset-x-0 z-50 transition-all duration-300 ${scrolled ? "py-3" : "py-5"}`}>
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className={`flex items-center justify-between gap-4 rounded-2xl px-4 sm:px-5 py-3 transition-all ${scrolled ? "glass-strong shadow-[0_10px_40px_-15px_rgba(0,0,0,0.6)]" : ""}`}>
          <a href="#" className="flex items-center gap-2 min-w-0">
            <div className="relative grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-gradient-brand ring-glow">
              <Sparkles className="h-4.5 w-4.5 text-white" strokeWidth={2.5} />
            </div>
            <span className="truncate font-bold tracking-tight text-[15px] sm:text-base">
              PortfolioForge
            </span>
          </a>

          <nav className="hidden md:flex items-center gap-1">
            {nav.map((n) => (
              <a key={n.label} href={n.href}
                 className="px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors rounded-md">
                {n.label}
              </a>
            ))}
          </nav>

          <div className="hidden md:flex items-center gap-2">
            <Link to="/builder" className="group inline-flex items-center gap-1.5 rounded-lg bg-gradient-brand px-4 py-2 text-sm font-semibold text-white ring-glow hover:scale-[1.02] active:scale-[0.98] transition-transform">
              Generate Portfolio
              <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>

          <button className="md:hidden grid h-9 w-9 place-items-center rounded-lg glass" onClick={() => setOpen(!open)} aria-label="Menu">
            {open ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}
          </button>
        </div>

        {open && (
          <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
            className="md:hidden mt-2 glass-strong rounded-2xl p-4 flex flex-col gap-1">
            {nav.map((n) => (
              <a key={n.label} href={n.href} onClick={() => setOpen(false)}
                className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground rounded-md">
                {n.label}
              </a>
            ))}
            <Link to="/builder" className="mt-1 inline-flex items-center justify-center gap-1.5 rounded-lg bg-gradient-brand px-4 py-2.5 text-sm font-semibold text-white">
              Generate Portfolio <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </motion.div>
        )}
      </div>
    </header>
  );
}

/* ───────────────────── hero ───────────────────── */

function Hero() {
  return (
    <section className="relative pt-36 sm:pt-44 pb-20 sm:pb-28 overflow-hidden">
      {/* Background fx */}
      <div className="pointer-events-none absolute inset-0 grid-bg" />
      <div className="pointer-events-none absolute -top-40 left-1/2 -translate-x-1/2 h-[600px] w-[1100px] rounded-full opacity-40 blur-3xl"
           style={{ background: "var(--gradient-aurora)" }} />
      <div className="pointer-events-none absolute top-20 right-[-100px] h-72 w-72 rounded-full bg-[oklch(0.74_0.15_210/0.25)] blur-3xl" />

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-[1.05fr_1fr] gap-12 lg:gap-14 items-center">
          {/* Left */}
          <div>
            <motion.div initial="hidden" animate="show" variants={fadeUp}
              className="inline-flex items-center gap-2 rounded-full glass px-3 py-1.5 text-xs font-medium text-muted-foreground">
              <span className="inline-block h-1.5 w-1.5 rounded-full bg-[var(--cyan-accent)] animate-pulse" />
              New: AI-Powered Portfolio Generation
            </motion.div>

            <motion.h1 initial="hidden" animate="show" custom={1} variants={fadeUp}
              className="mt-6 text-[40px] sm:text-6xl lg:text-[68px] leading-[1.05] tracking-tight font-extrabold">
              Build <span className="text-gradient-brand">Recruiter-Ready</span> Developer Portfolios in Minutes
            </motion.h1>

            <motion.p initial="hidden" animate="show" custom={2} variants={fadeUp}
              className="mt-6 text-base sm:text-lg text-muted-foreground max-w-xl leading-relaxed">
              Upload your resume, choose a theme, and generate a stunning professional portfolio website instantly — powered by AI.
            </motion.p>

            <motion.div initial="hidden" animate="show" custom={3} variants={fadeUp}
              className="mt-8 flex flex-wrap items-center gap-3">
              <Link to="/builder" className="group inline-flex items-center gap-2 rounded-xl bg-gradient-brand px-5 py-3 text-sm font-semibold text-white ring-glow hover:scale-[1.02] transition-transform">
                Generate Portfolio
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
              <a href="#templates" className="inline-flex items-center gap-2 rounded-xl glass px-5 py-3 text-sm font-semibold text-foreground hover:bg-white/5 transition-colors">
                View Templates
              </a>
            </motion.div>

            <motion.div initial="hidden" animate="show" custom={4} variants={fadeUp}
              className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
              {["No Coding Required", "AI Powered", "Free Starter Plan"].map((t) => (
                <span key={t} className="inline-flex items-center gap-1.5">
                  <Check className="h-4 w-4 text-[var(--cyan-accent)]" /> {t}
                </span>
              ))}
            </motion.div>
          </div>

          {/* Right — preview */}
          <PortfolioPreview />
        </div>
      </div>
    </section>
  );
}

function PortfolioPreview() {
  return (
    <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.9, delay: 0.2 }}
      className="relative">
      <div className="absolute -inset-6 bg-gradient-brand opacity-25 blur-3xl rounded-[40px]" />
      <div className="relative animate-float-slow">
        <div className="glass-strong rounded-3xl p-6 sm:p-7 shadow-[0_40px_120px_-30px_rgba(0,0,0,0.7)]">
          {/* window */}
          <div className="flex items-center gap-1.5 mb-5">
            <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.7_0.18_25)]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.78_0.15_85)]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[oklch(0.7_0.16_150)]" />
            <span className="ml-3 text-[11px] font-mono text-muted-foreground truncate">demo-user.portfolioforge.ai</span>
            <span className="ml-auto rounded-full border border-[var(--cyan-accent)]/30 bg-[var(--cyan-accent)]/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-widest text-[var(--cyan-accent)]">
              SAMPLE PORTFOLIO
            </span>
          </div>

          {/* profile */}
          <div className="flex items-center gap-4">
            <div className="relative h-14 w-14 shrink-0 rounded-2xl bg-gradient-brand grid place-items-center text-white font-bold text-lg ring-glow">
              {LANDING_DEMO.initials}
            </div>
            <div className="min-w-0">
              <div className="font-semibold tracking-tight truncate">{LANDING_DEMO.name}</div>
              <div className="text-xs text-muted-foreground truncate">{LANDING_DEMO.role} · {LANDING_DEMO.location}</div>
            </div>
            <div className="ml-auto hidden sm:flex items-center gap-1 rounded-full glass px-2.5 py-1 text-[10px] font-medium text-[var(--cyan-accent)]">
              <span className="h-1.5 w-1.5 rounded-full bg-[var(--cyan-accent)]" /> Open to work
            </div>
          </div>

          {/* score */}
          <div className="mt-5 rounded-2xl glass p-4">
            <p className="mb-3 text-xs leading-relaxed text-muted-foreground">{LANDING_DEMO.bio}</p>
            <div className="flex items-center justify-between text-xs text-muted-foreground mb-2">
              <span>Recruiter Readiness Score</span>
              <span className="font-mono text-foreground font-semibold">92<span className="text-muted-foreground">/100</span></span>
            </div>
            <div className="h-2 rounded-full bg-white/5 overflow-hidden">
              <motion.div initial={{ width: 0 }} animate={{ width: "92%" }} transition={{ duration: 1.4, delay: 0.6 }}
                className="h-full bg-gradient-brand rounded-full" />
            </div>
          </div>

          {/* stats */}
          <div className="mt-4 grid grid-cols-3 gap-3">
            {[
              { l: "Projects", v: "8" },
              { l: "Repos", v: "25" },
              { l: "Views", v: "1.2k" },
            ].map((s) => (
              <div key={s.l} className="rounded-xl glass p-3">
                <div className="text-lg font-bold tracking-tight">{s.v}</div>
                <div className="text-[10px] uppercase tracking-wider text-muted-foreground mt-0.5">{s.l}</div>
              </div>
            ))}
          </div>

          {/* tags */}
          <div className="mt-4 flex flex-wrap gap-1.5">
            {LANDING_DEMO.skills.map((t) => (
              <span key={t} className="rounded-md bg-white/5 border border-white/10 px-2 py-0.5 text-[10px] font-mono text-muted-foreground">{t}</span>
            ))}
          </div>

          <div className="mt-4 grid gap-2">
            {LANDING_DEMO.projects.map((project) => (
              <div key={project} className="rounded-xl glass px-3 py-2 text-xs font-medium text-foreground/90">
                {project}
              </div>
            ))}
          </div>
        </div>

        {/* floating chips */}
        <motion.div animate={{ y: [0, -10, 0] }} transition={{ duration: 5, repeat: Infinity }}
          className="absolute -top-5 -left-5 sm:-left-10 glass-strong rounded-xl px-3 py-2 flex items-center gap-2 shadow-lg">
          <Github className="h-4 w-4 text-[var(--cyan-accent)]" />
          <span className="text-xs font-medium">+12 repos synced</span>
        </motion.div>
        <motion.div animate={{ y: [0, 10, 0] }} transition={{ duration: 4.5, repeat: Infinity, delay: 0.5 }}
          className="absolute -bottom-4 -right-4 sm:-right-8 glass-strong rounded-xl px-3 py-2 flex items-center gap-2 shadow-lg">
          <Trophy className="h-4 w-4 text-[oklch(0.78_0.15_85)]" />
          <span className="text-xs font-medium">Hired at Razorpay</span>
        </motion.div>
      </div>
    </motion.div>
  );
}

/* ───────────────────── section header ───────────────────── */

function SectionHeader({ eyebrow, title, sub }: { eyebrow: string; title: React.ReactNode; sub?: string }) {
  return (
    <div className="max-w-2xl mx-auto text-center mb-14">
      <motion.div initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} variants={fadeUp}
        className="inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-[11px] font-medium uppercase tracking-wider text-[var(--cyan-accent)]">
        {eyebrow}
      </motion.div>
      <motion.h2 initial="hidden" whileInView="show" viewport={{ once: true }} custom={1} variants={fadeUp}
        className="mt-4 text-3xl sm:text-5xl font-extrabold tracking-tight leading-[1.1]">
        {title}
      </motion.h2>
      {sub && (
        <motion.p initial="hidden" whileInView="show" viewport={{ once: true }} custom={2} variants={fadeUp}
          className="mt-4 text-base text-muted-foreground">
          {sub}
        </motion.p>
      )}
    </div>
  );
}

/* ───────────────────── pipeline ───────────────────── */

const STEPS = [
  { icon: Upload, title: "Upload Resume", desc: "Drop in your PDF or DOCX resume — we handle the rest." },
  { icon: Brain, title: "AI Analysis", desc: "Extract skills, projects, education and experience automatically." },
  { icon: Palette, title: "Choose Theme", desc: "Pick from 50+ recruiter-tested professional themes." },
  { icon: Globe, title: "Generate Portfolio", desc: "Get a hosted, responsive portfolio website in seconds." },
  { icon: Rocket, title: "Share with Recruiters", desc: "One link. SEO-ready. Track views & engagement." },
];

function Pipeline() {
  return (
    <section id="how" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHeader eyebrow="Workflow" title={<>How <span className="text-gradient-brand">PortfolioForge</span> Works</>}
          sub="A five-step pipeline that turns your resume into a recruiter-ready portfolio." />

        <div className="relative grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-5">
          {/* connecting line on desktop */}
          <div className="hidden lg:block absolute top-12 left-[10%] right-[10%] h-px bg-gradient-to-r from-transparent via-white/15 to-transparent" />
          {STEPS.map((s, i) => (
            <motion.div key={s.title}
              initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} custom={i} variants={fadeUp}
              className="relative">
              <div className="glass rounded-2xl p-5 h-full hover:bg-white/[0.04] transition-colors group">
                <div className="flex items-center justify-between mb-4">
                  <div className="relative h-11 w-11 rounded-xl bg-gradient-brand grid place-items-center ring-glow group-hover:scale-110 transition-transform">
                    <s.icon className="h-5 w-5 text-white" strokeWidth={2.2} />
                  </div>
                  <span className="font-mono text-[11px] text-muted-foreground">0{i + 1}</span>
                </div>
                <h3 className="font-semibold tracking-tight">{s.title}</h3>
                <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">{s.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── stats ───────────────────── */

const STATS = [
  { value: "< 2 min", label: "Portfolio Generation", desc: "Generate a complete portfolio website from your resume in minutes." },
  { v: 100, suffix: "%", label: "Mobile Responsive", desc: "Looks great across desktop, tablet, and mobile devices." },
  { v: 6, suffix: "", label: "Themes Available", desc: "Choose from professionally designed portfolio themes." },
  { value: "24/7", label: "Portfolio Access", desc: "Your public portfolio link is available anytime, anywhere." },
];

function Stats() {
  return (
    <section className="relative py-16">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {STATS.map((s, i) => (
            <motion.div key={s.label}
              initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} custom={i} variants={fadeUp}
              className="glass-strong rounded-2xl p-6 text-center relative overflow-hidden group">
              <div className="absolute inset-0 opacity-0 group-hover:opacity-100 bg-gradient-brand transition-opacity duration-500 blur-2xl -z-10" style={{opacity: 0.08}} />
              <div className="text-4xl sm:text-5xl font-extrabold tracking-tight text-gradient-brand">
                {s.v !== undefined ? (
                  <Counter to={s.v} suffix={s.suffix} />
                ) : (
                  <motion.span initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.6, delay: i * 0.08 }}>
                    {s.value}
                  </motion.span>
                )}
              </div>
              <div className="mt-2 text-sm text-muted-foreground">{s.label}</div>
              <p className="mt-2 text-xs leading-relaxed text-muted-foreground/80">{s.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── features ───────────────────── */

const FEATURES = [
  { icon: FileText, title: "AI Resume Parsing", desc: "Auto-extract skills, projects, education and experience with high accuracy.", tag: "Powered by GPT-4" },
  { icon: Zap, title: "Portfolio Generator", desc: "Generate a complete developer portfolio website instantly — fully responsive.", tag: "< 30s build" },
  { icon: Layers, title: "Theme Marketplace", desc: "Choose from 50+ modern, recruiter-tested portfolio themes.", tag: "50+ themes" },
  { icon: Github, title: "GitHub Integration", desc: "Auto-pull repos, languages and contribution graph straight into your site.", tag: "Live sync" },
  { icon: Brain, title: "Role-Based Resume Suggestions", desc: "Get tailored improvement suggestions for your resume based on the role you're targeting.", tag: "AI insights" },
  { icon: Download, title: "One-Click Export", desc: "Export static HTML, deploy to Vercel, or share the hosted link instantly.", tag: "Deploy anywhere" },
];

function Features() {
  return (
    <section id="features" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHeader eyebrow="Features" title={<>Everything you need to <span className="text-gradient-brand">stand out</span></>}
          sub="A complete toolkit designed with recruiters and hiring managers in mind." />

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {FEATURES.map((f, i) => (
            <motion.div key={f.title}
              initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} custom={i % 3} variants={fadeUp}
              whileHover={{ y: -4 }}
              className="group relative glass rounded-2xl p-6 hover:bg-white/[0.05] transition-colors overflow-hidden">
              <div className="absolute -top-20 -right-20 h-40 w-40 rounded-full bg-gradient-brand opacity-0 group-hover:opacity-20 blur-3xl transition-opacity duration-500" />
              <div className="relative">
                <div className="flex items-center justify-between">
                  <div className="h-11 w-11 rounded-xl glass-strong grid place-items-center">
                    <f.icon className="h-5 w-5 text-[var(--cyan-accent)]" strokeWidth={2.2} />
                  </div>
                  <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground rounded-full glass px-2 py-1">{f.tag}</span>
                </div>
                <h3 className="mt-5 font-semibold tracking-tight text-lg">{f.title}</h3>
                <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── before / after ───────────────────── */

function BeforeAfter() {
  return (
    <section className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHeader eyebrow="Transformation" title={<>Transform your resume into a portfolio <span className="text-gradient-brand">recruiters love</span></>} />

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_auto_1fr] gap-6 lg:gap-4 items-center">
          {/* Before */}
          <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp}
            className="relative">
            <div className="absolute -top-3 left-4 z-10 inline-flex items-center gap-1.5 rounded-full bg-[oklch(0.3_0.04_265)] border border-white/10 px-2.5 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">
              Before · Plain Resume
            </div>
            <div className="bg-[oklch(0.95_0.01_90)] text-[oklch(0.2_0_0)] rounded-xl p-6 shadow-2xl rotate-[-1.5deg] font-mono text-[11px] leading-relaxed">
              <div className="text-center mb-3">
                <div className="text-base font-bold">DEMO USER</div>
                <div className="text-[10px]">Sample City · demo@example.com · +91 90000 00000</div>
              </div>
              <div className="border-t border-b border-black/20 py-1 mb-2 text-[10px] font-bold uppercase">Experience</div>
              <div className="space-y-1 mb-3">
                <div>• Built an AI Resume Analyzer with React and Node.js</div>
                <div>• Created a Portfolio Builder using TypeScript and Tailwind CSS</div>
                <div>• Shipped a Task Management Dashboard with Python services</div>
              </div>
              <div className="border-t border-b border-black/20 py-1 mb-2 text-[10px] font-bold uppercase">Skills</div>
              <div className="text-[10px]">{LANDING_DEMO.skills.join(", ")}</div>
              <div className="border-t border-b border-black/20 py-1 mb-2 mt-3 text-[10px] font-bold uppercase">Education</div>
              <div className="text-[10px]">B.E. Computer Science · VIT · 2025 · CGPA 8.9</div>
            </div>
          </motion.div>

          {/* arrow */}
          <motion.div initial={{ opacity: 0, scale: 0.5 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }}
            transition={{ delay: 0.3 }}
            className="hidden lg:grid place-items-center">
            <div className="relative h-14 w-14 rounded-full bg-gradient-brand grid place-items-center ring-glow">
              <ArrowRight className="h-6 w-6 text-white" />
              <div className="absolute inset-0 rounded-full bg-gradient-brand animate-ping opacity-30" />
            </div>
          </motion.div>

          {/* After */}
          <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} custom={2} variants={fadeUp}
            className="relative">
            <div className="absolute -top-3 right-4 z-10 inline-flex items-center gap-1.5 rounded-full bg-gradient-brand px-2.5 py-0.5 text-[10px] uppercase tracking-wider text-white">
              After · Live Portfolio
            </div>
            <div className="relative glass-strong rounded-xl p-5 rotate-[1.5deg] shadow-2xl">
              <div className="flex items-center gap-1.5 mb-4">
                <span className="h-2 w-2 rounded-full bg-white/30" />
                <span className="h-2 w-2 rounded-full bg-white/30" />
                <span className="h-2 w-2 rounded-full bg-white/30" />
              </div>
              <div className="space-y-3">
                <div className="h-24 rounded-lg bg-gradient-brand opacity-90 relative overflow-hidden">
                  <div className="absolute inset-0 grid-bg opacity-50" />
                  <div className="absolute bottom-2 left-3 text-white">
                    <div className="text-xs font-bold">{LANDING_DEMO.name}</div>
                    <div className="text-[10px] opacity-80">{LANDING_DEMO.role}</div>
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  {["92", "8", "25"].map((n, i) => (
                    <div key={i} className="rounded-md glass p-2 text-center">
                      <div className="text-sm font-bold text-gradient-brand">{n}</div>
                      <div className="text-[8px] uppercase text-muted-foreground">{["Score","Projects","Repos"][i]}</div>
                    </div>
                  ))}
                </div>
                <div className="space-y-1.5">
                  <div className="h-2 rounded bg-white/10 w-full" />
                  <div className="h-2 rounded bg-white/10 w-4/5" />
                  <div className="h-2 rounded bg-white/10 w-3/5" />
                </div>
                <div className="flex gap-1.5 flex-wrap">
                  {["React","TS","Node","Py"].map((t) => (
                    <span key={t} className="text-[9px] font-mono rounded bg-[var(--cyan-accent)]/15 text-[var(--cyan-accent)] px-1.5 py-0.5">{t}</span>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── themes ───────────────────── */

const THEMES = [
  { name: "Corporate Professional", tag: "Classic", colors: ["#1e293b","#334155","#3b82f6"], vibe: "corporate" },
  { name: "Modern SaaS", tag: "Popular", colors: ["#0f172a","#6366f1","#06b6d4"], vibe: "saas" },
  { name: "Glassmorphism Pro", tag: "Premium", colors: ["#0b1120","#a78bfa","#22d3ee"], vibe: "glass" },
  { name: "Cyberpunk Developer", tag: "Bold", colors: ["#0a0a0a","#ec4899","#22d3ee"], vibe: "cyber" },
  { name: "Developer Terminal", tag: "Minimal", colors: ["#000000","#10b981","#a3e635"], vibe: "terminal" },
  { name: "Creative Designer", tag: "Artistic", colors: ["#fef3c7","#f97316","#7c3aed"], vibe: "creative" },
];

function ThemePreview({ vibe, colors }: { vibe: string; colors: string[] }) {
  if (vibe === "terminal") {
    return (
      <div className="h-full w-full font-mono text-[10px] p-3" style={{ background: colors[0], color: colors[1] }}>
        <div className="opacity-60">$ whoami</div>
        <div>demo_user</div>
        <div className="opacity-60 mt-1">$ cat skills.txt</div>
        <div style={{ color: colors[2] }}>react · ts · node · python</div>
        <div className="opacity-60 mt-1">$ ls projects/</div>
        <div>resume-analyzer/ portfolio-builder/ task-dashboard/</div>
        <div className="mt-1 inline-block h-2.5 w-1.5 animate-pulse" style={{background: colors[1]}} />
      </div>
    );
  }
  if (vibe === "cyber") {
    return (
      <div className="h-full w-full p-3 relative overflow-hidden" style={{background: colors[0]}}>
        <div className="absolute inset-0 grid-bg opacity-40" />
        <div className="relative text-[11px] font-bold uppercase tracking-widest" style={{color: colors[1]}}>DEMO USER</div>
        <div className="relative text-[9px]" style={{color: colors[2]}}>// full stack dev</div>
        <div className="mt-3 h-6 rounded-sm" style={{background: `linear-gradient(90deg, ${colors[1]}, ${colors[2]})`}} />
        <div className="mt-1.5 grid grid-cols-3 gap-1">
          {[0,1,2].map(i => <div key={i} className="h-4 rounded-sm" style={{background: i === 1 ? colors[2] : colors[1], opacity: 0.4}} />)}
        </div>
      </div>
    );
  }
  if (vibe === "creative") {
    return (
      <div className="h-full w-full p-3" style={{background: colors[0]}}>
        <div className="h-8 w-8 rounded-full" style={{background: colors[1]}} />
        <div className="mt-2 text-xs font-bold" style={{color: colors[2]}}>{LANDING_DEMO.name}</div>
        <div className="text-[9px]" style={{color: colors[1]}}>creative coder</div>
        <div className="mt-2 grid grid-cols-2 gap-1">
          <div className="h-6 rounded" style={{background: colors[1], opacity: 0.7}} />
          <div className="h-6 rounded" style={{background: colors[2], opacity: 0.7}} />
        </div>
      </div>
    );
  }
  // saas / corporate / glass
  return (
    <div className="h-full w-full p-3 relative" style={{background: colors[0]}}>
      {vibe === "glass" && <div className="absolute inset-0 grid-bg opacity-40" />}
      <div className="relative">
        <div className="h-10 rounded-md mb-2" style={{background: `linear-gradient(135deg, ${colors[1]}, ${colors[2]})`}} />
        <div className="text-[10px] font-bold text-white">{LANDING_DEMO.name}</div>
        <div className="text-[8px] text-white/60">{LANDING_DEMO.role}</div>
        <div className="mt-2 grid grid-cols-3 gap-1">
          {[0,1,2].map(i => (
            <div key={i} className="h-7 rounded" style={{background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.1)'}}>
              <div className="h-full grid place-items-center text-[8px] text-white font-bold">{[92,8,25][i]}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function Themes() {
  return (
    <section id="templates" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHeader eyebrow="Templates" title={<>Pick a <span className="text-gradient-brand">stunning theme</span></>}
          sub="Every template is responsive, SEO-optimized and built to impress recruiters." />

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {THEMES.map((t, i) => (
            <motion.div key={t.name}
              initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} custom={i % 3} variants={fadeUp}
              whileHover={{ y: -6 }}
              className="group glass rounded-2xl p-3 hover:bg-white/[0.05] transition-colors">
              <div className="aspect-[4/3] rounded-xl overflow-hidden border border-white/10 relative">
                <ThemePreview vibe={t.vibe} colors={t.colors} />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity grid place-items-end p-3">
                  <button className="w-full rounded-lg bg-gradient-brand py-2 text-xs font-semibold text-white">Select Theme</button>
                </div>
              </div>
              <div className="flex items-center justify-between mt-3 px-1">
                <div>
                  <div className="font-semibold text-sm tracking-tight">{t.name}</div>
                  <div className="text-[10px] text-muted-foreground">Responsive · SEO-ready</div>
                </div>
                <span className="text-[10px] font-mono rounded-md glass px-2 py-1 text-[var(--cyan-accent)]">{t.tag}</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── built for ───────────────────── */

const AUDIENCES = [
  { icon: GraduationCap, title: "Final Year Students", desc: "Showcase capstone projects and academic work." },
  { icon: Rocket, title: "Freshers", desc: "Stand out without years of work experience." },
  { icon: Code2, title: "Frontend Developers", desc: "Highlight UI work, design systems and live demos." },
  { icon: Layers, title: "Full Stack Developers", desc: "Show end-to-end architecture and product thinking." },
  { icon: Cpu, title: "AI Engineers", desc: "Demonstrate models, notebooks and ML pipelines." },
  { icon: Trophy, title: "Hackathon Participants", desc: "Turn every hack into a polished case study." },
];

function BuiltFor() {
  return (
    <section id="about" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHeader eyebrow="Built For" title={<>Made for <span className="text-gradient-brand">developers like you</span></>} />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {AUDIENCES.map((a, i) => (
            <motion.div key={a.title}
              initial="hidden" whileInView="show" viewport={{ once: true, margin: "-50px" }} custom={i % 3} variants={fadeUp}
              className="glass rounded-2xl p-5 flex items-start gap-4 hover:bg-white/[0.05] transition-colors">
              <div className="h-10 w-10 shrink-0 rounded-xl bg-gradient-brand grid place-items-center">
                <a.icon className="h-5 w-5 text-white" strokeWidth={2.2} />
              </div>
              <div className="min-w-0">
                <div className="font-semibold tracking-tight">{a.title}</div>
                <div className="text-sm text-muted-foreground mt-0.5">{a.desc}</div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── github widget ───────────────────── */

function GitHubWidget() {
  const langs = [
    { n: "React", v: 38, c: "var(--cyan-accent)" },
    { n: "Python", v: 26, c: "oklch(0.78 0.15 85)" },
    { n: "Flask", v: 18, c: "oklch(0.65 0.18 320)" },
    { n: "JavaScript", v: 18, c: "oklch(0.72 0.18 60)" },
  ];

  return (
    <section className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-[11px] font-medium uppercase tracking-wider text-[var(--cyan-accent)]">
              GitHub Integration
            </div>
            <h2 className="mt-4 text-3xl sm:text-5xl font-extrabold tracking-tight leading-[1.1]">
              Your code, <span className="text-gradient-brand">beautifully showcased</span>
            </h2>
            <p className="mt-5 text-muted-foreground leading-relaxed">
              Sync your GitHub in one click. We surface your best repos, language breakdown,
              contribution graph and pinned projects — auto-updating as you push.
            </p>
            <ul className="mt-6 space-y-3 text-sm">
              {["Live repo & star count", "Language analytics", "Contribution heatmap", "Auto-curated pinned projects"].map((x) => (
                <li key={x} className="flex items-center gap-2">
                  <Check className="h-4 w-4 text-[var(--cyan-accent)]" />
                  <span className="text-muted-foreground">{x}</span>
                </li>
              ))}
            </ul>
          </div>

          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="glass-strong rounded-3xl p-6 sm:p-7 shadow-[0_40px_120px_-30px_rgba(0,0,0,0.7)]">
            <div className="flex items-center gap-3 mb-5">
              <div className="h-11 w-11 rounded-xl bg-[oklch(0.2_0_0)] grid place-items-center">
                <Github className="h-5 w-5 text-white" />
              </div>
              <div className="min-w-0">
                <div className="font-semibold tracking-tight truncate">{LANDING_DEMO.githubUsername}</div>
                <div className="text-xs text-muted-foreground">github.com/{LANDING_DEMO.githubUsername}</div>
              </div>
              <div className="ml-auto rounded-md glass px-2 py-1 text-[10px] font-mono">Connected</div>
            </div>

            <div className="grid grid-cols-3 gap-3 mb-5">
              {[{l:"Repos",v:"25"},{l:"Stars",v:"48"},{l:"Forks",v:"12"}].map((s) => (
                <div key={s.l} className="rounded-xl glass p-3 text-center">
                  <div className="text-xl font-bold tracking-tight">{s.v}</div>
                  <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{s.l}</div>
                </div>
              ))}
            </div>

            <div className="mb-5">
              <div className="text-xs text-muted-foreground mb-2">Top languages</div>
              <div className="flex h-2 rounded-full overflow-hidden mb-2">
                {langs.map((l) => (
                  <div key={l.n} style={{ width: `${l.v}%`, background: l.c }} />
                ))}
              </div>
              <div className="flex flex-wrap gap-x-3 gap-y-1 text-[11px]">
                {langs.map((l) => (
                  <span key={l.n} className="inline-flex items-center gap-1.5 text-muted-foreground">
                    <span className="h-2 w-2 rounded-full" style={{ background: l.c }} />
                    {l.n} <span className="opacity-60">{l.v}%</span>
                  </span>
                ))}
              </div>
            </div>

            <div>
              <div className="text-xs text-muted-foreground mb-2">Contributions · last 6 months</div>
              <div className="grid grid-cols-[repeat(26,minmax(0,1fr))] gap-[3px]">
                {Array.from({ length: 26 * 7 }).map((_, i) => {
                  const intensity = Math.abs(Math.sin(i * 100)) % 1;
                  const lvl = intensity > 0.85 ? 4 : intensity > 0.65 ? 3 : intensity > 0.4 ? 2 : intensity > 0.2 ? 1 : 0;
                  const colors = ["rgba(255,255,255,0.05)","oklch(0.4_0.12_277)","oklch(0.55_0.18_265)","oklch(0.65_0.2_250)","oklch(0.75_0.16_210)"];
                  return <div key={i} className="aspect-square rounded-[2px]" style={{ background: colors[lvl] }} />;
                })}
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── final CTA ───────────────────── */

function FinalCTA() {
  return (
    <section id="cta" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="relative glass-strong rounded-[32px] overflow-hidden px-6 sm:px-12 py-16 sm:py-20 text-center">
          <div className="absolute inset-0 opacity-50" style={{ background: "var(--gradient-aurora)" }} />
          <div className="absolute inset-0 backdrop-blur-3xl" />
          <div className="absolute inset-0 grid-bg opacity-40" />

          <div className="relative">
            <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp}
              className="inline-flex items-center gap-2 rounded-full glass-strong px-3 py-1.5 text-xs font-medium">
              <Sparkles className="h-3.5 w-3.5 text-[var(--cyan-accent)]" />
              Free starter plan · No credit card
            </motion.div>

            <motion.h2 initial="hidden" whileInView="show" viewport={{ once: true }} custom={1} variants={fadeUp}
              className="mt-5 text-4xl sm:text-6xl font-extrabold tracking-tight leading-[1.05]">
              Ready to build your <span className="text-gradient-brand">portfolio?</span>
            </motion.h2>
            <motion.p initial="hidden" whileInView="show" viewport={{ once: true }} custom={2} variants={fadeUp}
              className="mt-5 max-w-xl mx-auto text-muted-foreground">
              Generate a professional developer portfolio in minutes. Join 5,000+ developers who already shipped theirs.
            </motion.p>
            <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} custom={3} variants={fadeUp}
              className="mt-9 flex flex-wrap items-center justify-center gap-3">
              <Link to="/builder" className="group inline-flex items-center gap-2 rounded-xl bg-gradient-brand px-6 py-3.5 text-sm font-semibold text-white ring-glow hover:scale-[1.02] transition-transform">
                Generate Portfolio
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
              <a href="#templates" className="inline-flex items-center gap-2 rounded-xl glass-strong px-6 py-3.5 text-sm font-semibold text-foreground hover:bg-white/10 transition-colors">
                Explore Templates
              </a>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ───────────────────── footer ───────────────────── */

function Footer() {
  return (
    <footer className="relative border-t border-white/5 pt-16 pb-10">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid grid-cols-1 md:grid-cols-[1.4fr_1fr_1fr_1fr] gap-10 mb-12">
          <div>
            <div className="flex items-center gap-2">
              <div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-brand">
                <Sparkles className="h-4.5 w-4.5 text-white" />
              </div>
              <span className="font-bold tracking-tight">PortfolioForge</span>
            </div>
            <p className="mt-4 text-sm text-muted-foreground max-w-xs leading-relaxed">
              The fastest way to build recruiter-ready developer portfolios from your resume.
            </p>
            <div className="mt-5 flex gap-2">
              {[Github, Linkedin, Twitter].map((I, i) => (
                <a key={i} href="#" className="grid h-9 w-9 place-items-center rounded-lg glass hover:bg-white/10 transition-colors">
                  <I className="h-4 w-4" />
                </a>
              ))}
            </div>
          </div>

          {[
            { title: "Product", links: ["Features", "Templates", "Pricing", "Changelog"] },
            { title: "Company", links: ["About", "Contact", "Blog", "Careers"] },
            { title: "Legal", links: ["Privacy Policy", "Terms", "Security", "Cookies"] },
          ].map((col) => (
            <div key={col.title}>
              <div className="text-xs font-semibold uppercase tracking-wider text-foreground mb-4">{col.title}</div>
              <ul className="space-y-2.5">
                {col.links.map((l) => (
                  <li key={l}>
                    <a href="#" className="text-sm text-muted-foreground hover:text-foreground transition-colors">{l}</a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="pt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="text-xs text-muted-foreground">© 2026 PortfolioForge. All rights reserved.</div>
          <div className="text-xs text-muted-foreground inline-flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[oklch(0.7_0.16_150)] animate-pulse" />
            All systems operational
          </div>
        </div>
      </div>
    </footer>
  );
}

/* ───────────────────── page ───────────────────── */

export default function Landing() {
  return (
    <main className="relative min-h-screen overflow-hidden">
      <Navbar />
      <Hero />
      <Pipeline />
      <Stats />
      <Features />
      <BeforeAfter />
      <Themes />
      <BuiltFor />
      <GitHubWidget />
      <FinalCTA />
      <Footer />
    </main>
  );
}
